name: "Prepare android environment for build"
description: "Clone, Download jdk, android sdk, etc"
runs:
  using: "composite"
  steps:

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set wrapper permission
      shell: bash
      run: chmod +x ./gradlew

