name: PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Set wrapper permission
        run: chmod +x ./gradlew

      - name: Assemble Debug
        run: ./gradlew assembleDebug

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Set wrapper permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --stacktrace

  Upload-Artifacts:
    runs-on: ubuntu-latest
    needs: [Build, Unit-Tests]
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
              app/build/reports
              app/build/outputs/apk/debug/*.apk
